# PowerShell script to bundle modular Roblox scripts into a single executable file

$srcDir = "src"
$distDir = "dist"
$outputFile = "$distDir\bundle.lua"

if (-not (Test-Path $srcDir)) {
    Write-Error "Source directory '$srcDir' does not exist."
    exit 1
}

# Create dist directory if it doesn't exist
if (-not (Test-Path $distDir)) {
    New-Item -ItemType Directory -Path $distDir | Out-Null
}

Write-Host "Bundling files..." -ForegroundColor Green

# Start building the virtual filesystem string
$bundleContent = @"
-- BUNDLED SCRIPT GENERATED BY BUILDER
-- Date: $(Get-Date)

local _virtual_files = {}
"@

# Recursively get all lua files in src
$files = Get-ChildItem -Path $srcDir -Filter *.lua -Recurse

foreach ($file in $files) {
    # Get path relative to the root directory (using forward slashes)
    $relativePath = "src/" + (Resolve-Path $file.FullName -Relative).Replace(".\src\", "").Replace("\", "/")
    
    # Skip main.lua since it is the entry point and will be appended at the end
    if ($relativePath -eq "src/main.lua") {
        continue
    }

    $fileContent = Get-Content -Raw -Path $file.FullName
    # Escape any Lua long brackets [[ ]] if present, or format nicely.
    # To prevent syntax issues, we use custom long brackets e.g. [===[ ... ]===]
    $escapedContent = "`n" + $fileContent + "`n"
    
    $bundleContent += "`n_virtual_files[`"$relativePath`"] = [=====[" + $escapedContent + "]=====]`n"
    Write-Host "-> Packed: $relativePath" -ForegroundColor Cyan
}

# Add custom loader override
$bundleContent += @"

-- Virtual File System Loader Override
local original_readfile = readfile
local function readfile(path)
    -- Normalize path separators to forward slashes
    local normalized_path = string.gsub(path, "\\\\", "/")
    if _virtual_files[normalized_path] then
        return _virtual_files[normalized_path]
    end
    if original_readfile then
        return original_readfile(path)
    end
    error("File not found in virtual bundle: " .. tostring(path))
end

-- Hook loadstring to use the virtual environment
local original_loadstring = loadstring
local function loadstring(content, chunkname)
    return original_loadstring(content, chunkname)
end
"@

# Read main.lua and append it to the end of the bundle
if (Test-Path "$srcDir\main.lua") {
    $mainContent = Get-Content -Raw -Path "$srcDir\main.lua"
    # Prepend local override of readfile for main.lua environment
    $bundleContent += "`n`n-- Entry Point: main.lua`n"
    $bundleContent += "local readfile = readfile`n"
    $bundleContent += $mainContent
    Write-Host "-> Appended entry: src/main.lua" -ForegroundColor Cyan
} else {
    Write-Error "Entry point '$srcDir\main.lua' not found!"
    exit 1
}

# Write the final bundled script to dist/bundle.lua
Set-Content -Path $outputFile -Value $bundleContent -Encoding utf8
Write-Host "Bundle successfully generated: $outputFile" -ForegroundColor Green
